import { ApolloClient, ApolloProvider } from "@apollo/client";

import "@/styles/globals.scss";
import Footer from "../components/Footer";
import Navbar from "../components/navbar/Navbar";
import { ProviderWrapper } from "../store";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const client = new ApolloClient({
  cache,
  uri: "http://localhost:4000/graphql",
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ProviderWrapper>
          <ApolloProvider client={client}>
            <Navbar />
            {children}
            <Footer />
          </ApolloProvider>
        </ProviderWrapper>
      </body>
    </html>
  );
}
