import "@/styles/globals.scss";
import Footer from "../components/Footer";
import Navbar from "../components/navbar/Navbar";
import { ProviderWrapper } from "../store";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ProviderWrapper>
          <Navbar />
          {children}
          <Footer />
        </ProviderWrapper>
      </body>
    </html>
  );
}
